FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app
ARG PROJECT_NAME=Hangman

# Copy csproj and restore as distinct layers
COPY . ./
RUN dotnet restore $PROJECT_NAME/$PROJECT_NAME.csproj

# Setting dotnet ef available
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"